#!/bin/bash
# Helpers for the /sentinel-autoresearch command.
#
# This script is not meant to be run standalone — the autoresearch command
# sources it (or calls individual functions via `bash autoresearch-helpers.sh <fn> <args>`)
# to keep the command markdown focused on orchestration rather than plumbing.
#
# All functions are designed to be safe to call repeatedly and to write state
# to disk immediately so that a crash mid-iteration leaves a resumable run.
#
# Dispatchable entry point:
#   bash autoresearch-helpers.sh <function_name> [args...]
#
# Available functions (see each for arg details):
#   ar_preflight <score_cmd> [--allow-dirty]
#   ar_init_run <run_id> <task> <score_cmd> <objective> <mode> <budget_seconds> <max_iter> <target> <branch_prefix> <constraints_src>
#   ar_run_score <run_id>                 -> prints number on stdout, or "ERROR" on failure
#   ar_append_tsv <run_id> <iteration> <status> <score> <delta> <commit> <description>
#   ar_commit_kept <run_id> <iteration> <score> <description>  -> prints commit SHA
#   ar_discard_working_tree
#   ar_update_state <run_id> <jq_filter>  -> applies jq update in place
#   ar_is_improvement <objective> <score> <best>  -> exits 0 if improvement, 1 otherwise
#   ar_list_runs
#   ar_report <run_id>

set -uo pipefail

# ─── Path helpers ────────────────────────────────────────────────────────────

ar_run_dir() {
    echo ".sentinel/autoresearch/${1}"
}

ar_state_file() {
    echo ".sentinel/autoresearch/${1}/state.json"
}

ar_tsv_file() {
    echo ".sentinel/autoresearch/${1}/attempts.tsv"
}

ar_constraints_file() {
    echo ".sentinel/autoresearch/${1}/constraints.md"
}

ar_score_script() {
    echo ".sentinel/autoresearch/${1}/score.sh"
}

# ─── Preflight ───────────────────────────────────────────────────────────────

ar_preflight() {
    local score_cmd="${1:-}"
    local allow_dirty="${2:-false}"

    if [ -z "$score_cmd" ]; then
        echo "ERROR: ar_preflight requires a score command" >&2
        return 1
    fi

    if ! git rev-parse --git-dir >/dev/null 2>&1; then
        echo "ERROR: /sentinel-autoresearch requires a git repository." >&2
        echo "       cd into a git repo or run 'git init' first." >&2
        return 1
    fi

    if [ "$allow_dirty" != "true" ]; then
        if [ -n "$(git status --porcelain)" ]; then
            echo "ERROR: working tree is dirty. Commit or stash changes, or re-run with --allow-dirty." >&2
            git status --short >&2
            return 1
        fi
    fi

    if ! command -v jq >/dev/null 2>&1; then
        echo "ERROR: jq is required. Install it or run a sentinel session start hook first." >&2
        return 1
    fi

    return 0
}

# ─── Initialize run ──────────────────────────────────────────────────────────

ar_init_run() {
    local run_id="$1"
    local task="$2"
    local score_cmd="$3"
    local objective="${4:-max}"
    local mode="${5:-budget}"
    local budget_seconds="${6:-0}"
    local max_iter="${7:-0}"
    local target="${8:-}"
    local branch_prefix="${9:-autoresearch}"
    local constraints_src="${10:-}"

    local run_dir
    run_dir="$(ar_run_dir "$run_id")"
    mkdir -p "$run_dir"

    # Ensure .sentinel/ is never tracked by git for this repo.
    # We use .git/info/exclude (local, uncommitted) so we don't mutate the
    # user's .gitignore. Without this, `git add -A` during an iteration would
    # commit the TSV/state files, and `git reset --hard HEAD` during a discard
    # would then wipe updates to them — destroying the ledger.
    local exclude_file=".git/info/exclude"
    if [ -d .git ] && [ -f "$exclude_file" ]; then
        if ! grep -qxF '.sentinel/' "$exclude_file" 2>/dev/null; then
            printf '\n# autoresearch: never track sentinel state/ledger files\n.sentinel/\n' >> "$exclude_file"
        fi
    fi
    # If .sentinel is already tracked for some reason, untrack it (keeps files).
    if git ls-files --error-unmatch .sentinel >/dev/null 2>&1; then
        git rm -r --cached .sentinel >/dev/null 2>&1 || true
    fi

    local branch="${branch_prefix}/${run_id}"
    local base_commit
    base_commit=$(git rev-parse HEAD 2>/dev/null || echo "")

    if [ -z "$base_commit" ]; then
        echo "ERROR: repo has no commits yet. Make at least one commit before running autoresearch." >&2
        return 1
    fi

    # Create the branch if it doesn't exist; switch to it either way.
    if git show-ref --verify --quiet "refs/heads/${branch}"; then
        git checkout "$branch" >/dev/null 2>&1
    else
        git checkout -b "$branch" >/dev/null 2>&1
    fi

    # Persist the score command verbatim so resumes run the same thing.
    local score_script
    score_script="$(ar_score_script "$run_id")"
    {
        echo "#!/bin/bash"
        echo "# Auto-generated by /sentinel-autoresearch. Do not edit by hand."
        echo "# This is the score command for run ${run_id}."
        echo "set -uo pipefail"
        echo "$score_cmd"
    } > "$score_script"
    chmod +x "$score_script"

    # Write the constraints file.
    local constraints_file
    constraints_file="$(ar_constraints_file "$run_id")"
    if [ -n "$constraints_src" ] && [ -f "$constraints_src" ]; then
        cp "$constraints_src" "$constraints_file"
    else
        cat > "$constraints_file" <<EOF
# Autoresearch constraints for run ${run_id}

## Task
${task}

## What the agent MAY change
- Any file relevant to the task. Tighten this if possible.

## What the agent MUST NOT change
- The score command (recorded in score.sh for this run)
- The task definition above
- Package/dependency files (pyproject.toml, package.json, requirements.txt, Cargo.toml, go.mod)
  unless the task is explicitly about dependencies
- Test files, unless the task is explicitly about improving or adding tests
  (never delete or weaken a test to improve the score)

## Simplicity criterion
A tiny improvement that adds significant complexity is NOT worth keeping.
Simplification wins (same-or-better score with less code) are always good.

## Autonomy
Do not stop to ask questions. Propose an edit, apply it, score it, log it, repeat.
EOF
    fi

    # Initialize the TSV ledger with a header row.
    local tsv
    tsv="$(ar_tsv_file "$run_id")"
    printf 'iteration\ttimestamp\tstatus\tscore\tdelta_vs_best\tcommit\tdescription\n' > "$tsv"

    # Initialize state.json with placeholders; baseline is added after scoring.
    local state
    state="$(ar_state_file "$run_id")"
    local now
    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    jq -n \
        --arg run_id "$run_id" \
        --arg task "$task" \
        --arg score_cmd "$score_cmd" \
        --arg objective "$objective" \
        --arg mode "$mode" \
        --argjson budget_seconds "$budget_seconds" \
        --argjson max_iter "$max_iter" \
        --arg target "$target" \
        --arg now "$now" \
        --arg branch "$branch" \
        --arg base_commit "$base_commit" \
        '{
            type: "autoresearch",
            run_id: $run_id,
            task: $task,
            score_command: $score_cmd,
            objective: $objective,
            mode: $mode,
            budget_seconds: $budget_seconds,
            max_iterations: $max_iter,
            target: (if $target == "" then null else ($target | tonumber? // $target) end),
            status: "running",
            started_at: $now,
            ended_at: null,
            branch: $branch,
            base_commit: $base_commit,
            baseline_score: null,
            best_score: null,
            best_commit: $base_commit,
            iterations: 0,
            kept: 0,
            discarded: 0,
            errors: 0,
            consecutive_no_improvement: 0,
            last_attempt: null
        }' > "$state"

    echo "$run_dir"
    return 0
}

# ─── Scoring ─────────────────────────────────────────────────────────────────

ar_run_score() {
    local run_id="$1"
    local script
    script="$(ar_score_script "$run_id")"

    if [ ! -x "$script" ]; then
        echo "ERROR: score script not found or not executable: $script" >&2
        echo "ERROR"
        return 1
    fi

    local output
    if ! output=$("$script" 2>&1); then
        echo "ERROR"
        return 1
    fi

    # Extract the last numeric token on the last non-empty line of stdout.
    # Uses awk (not grep -oE) for portability: BSD grep on macOS interprets
    # a leading "-?" in the pattern as a flag.
    local number
    number=$(printf '%s' "$output" | awk 'NF' | tail -1 | awk '{
        for (i = 1; i <= NF; i++) {
            if ($i ~ /^-?[0-9]+(\.[0-9]+)?$/) n = $i
        }
        print n
    }')

    if [ -z "$number" ]; then
        echo "ERROR"
        return 1
    fi

    echo "$number"
    return 0
}

# ─── Ledger ──────────────────────────────────────────────────────────────────

ar_append_tsv() {
    local run_id="$1"
    local iteration="$2"
    local status="$3"
    local score="${4:-}"
    local delta="${5:-}"
    local commit="${6:--}"
    local description="${7:-}"

    local tsv
    tsv="$(ar_tsv_file "$run_id")"
    local now
    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Sanitize tabs and newlines out of the description so we don't corrupt the TSV.
    description=$(printf '%s' "$description" | tr '\t\n' '  ')

    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$iteration" "$now" "$status" "${score:--}" "${delta:--}" "$commit" "$description" >> "$tsv"
}

# ─── Git keep / discard ──────────────────────────────────────────────────────

ar_commit_kept() {
    local run_id="$1"
    local iteration="$2"
    local score="$3"
    local description="$4"

    # Strip tabs and newlines from the commit message for safety.
    local msg
    msg=$(printf 'autoresearch[%s]: %s [score=%s]' \
        "$iteration" "$(printf '%s' "$description" | tr '\t\n' '  ')" "$score")

    git add -A >/dev/null 2>&1

    # If nothing actually changed (edit was a no-op), treat as discard.
    if git diff --cached --quiet; then
        return 2
    fi

    if ! git commit -m "$msg" --no-verify >/dev/null 2>&1; then
        echo "ERROR: git commit failed for iteration $iteration" >&2
        return 1
    fi

    git rev-parse HEAD
    return 0
}

ar_discard_working_tree() {
    # Throw away anything the agent did this iteration. Safe on clean tree.
    git reset --hard HEAD >/dev/null 2>&1 || true
    # Clean untracked files too, but preserve the .sentinel dir.
    git clean -fd --exclude='.sentinel' >/dev/null 2>&1 || true
}

# ─── State updates ───────────────────────────────────────────────────────────

ar_update_state() {
    local run_id="$1"
    local jq_filter="$2"

    local state
    state="$(ar_state_file "$run_id")"
    local tmp
    tmp=$(mktemp)
    if jq "$jq_filter" "$state" > "$tmp"; then
        mv "$tmp" "$state"
    else
        rm -f "$tmp"
        echo "ERROR: jq update failed: $jq_filter" >&2
        return 1
    fi
}

# ─── Objective comparison ────────────────────────────────────────────────────

# Returns 0 if $2 is strictly better than $3 under $1 (max|min).
# If $3 is empty/null, any real number is an improvement.
ar_is_improvement() {
    local objective="$1"
    local score="$2"
    local best="$3"

    if [ -z "$best" ] || [ "$best" = "null" ]; then
        return 0
    fi

    if [ "$objective" = "min" ]; then
        awk "BEGIN { exit ($score < $best) ? 0 : 1 }"
    else
        awk "BEGIN { exit ($score > $best) ? 0 : 1 }"
    fi
}

# ─── Listing and reporting ───────────────────────────────────────────────────

ar_list_runs() {
    local base=".sentinel/autoresearch"
    if [ ! -d "$base" ]; then
        echo "No autoresearch runs found."
        return 0
    fi

    printf '%-40s  %-10s  %-10s  %-10s  %s\n' \
        "RUN_ID" "STATUS" "BASELINE" "BEST" "TASK"
    printf '%-40s  %-10s  %-10s  %-10s  %s\n' \
        "$(printf '%.0s-' {1..40})" "----------" "----------" "----------" "----"

    local any=0
    for state in "$base"/*/state.json; do
        [ -f "$state" ] || continue
        any=1
        local run_id status baseline best task
        run_id=$(jq -r '.run_id' "$state")
        status=$(jq -r '.status' "$state")
        baseline=$(jq -r '.baseline_score // "-"' "$state")
        best=$(jq -r '.best_score // "-"' "$state")
        task=$(jq -r '.task' "$state" | cut -c1-50)
        printf '%-40s  %-10s  %-10s  %-10s  %s\n' \
            "$run_id" "$status" "$baseline" "$best" "$task"
    done

    if [ "$any" = "0" ]; then
        echo "No autoresearch runs found."
    fi
}

ar_report() {
    local run_id="${1:-}"
    local base=".sentinel/autoresearch"

    if [ -z "$run_id" ]; then
        # Pick the most recently modified run.
        run_id=$(ls -t "$base" 2>/dev/null | head -1)
        if [ -z "$run_id" ]; then
            echo "No autoresearch runs found."
            return 1
        fi
    fi

    local state tsv
    state="$(ar_state_file "$run_id")"
    tsv="$(ar_tsv_file "$run_id")"

    if [ ! -f "$state" ]; then
        echo "ERROR: run '$run_id' not found at $state" >&2
        return 1
    fi

    echo "=== autoresearch run: $run_id ==="
    jq -r '
        "Task:         \(.task)",
        "Objective:    \(.objective)",
        "Mode:         \(.mode)",
        "Status:       \(.status)",
        "Branch:       \(.branch)",
        "Started:      \(.started_at)",
        "Ended:        \(.ended_at // "(still running)")",
        "Baseline:     \(.baseline_score // "-")",
        "Best score:   \(.best_score // "-")",
        "Best commit:  \(.best_commit // "-")",
        "Iterations:   \(.iterations) (kept: \(.kept), discarded: \(.discarded), errors: \(.errors))"
    ' "$state"
    echo ""

    if [ -f "$tsv" ]; then
        local rows
        rows=$(($(wc -l < "$tsv") - 1))
        echo "Ledger: $tsv ($rows attempts)"
        echo ""
        echo "--- First 3 attempts ---"
        head -4 "$tsv" | column -t -s $'\t'
        if [ "$rows" -gt 6 ]; then
            echo ""
            echo "--- Last 3 attempts ---"
            tail -3 "$tsv" | column -t -s $'\t'
        fi
    fi
}

# ─── Dispatcher ──────────────────────────────────────────────────────────────

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    # Called directly — dispatch to the named function.
    fn="${1:-}"
    if [ -z "$fn" ]; then
        echo "Usage: $0 <function> [args...]" >&2
        echo "See the top of this file for available functions." >&2
        exit 1
    fi
    shift
    if ! declare -F "$fn" >/dev/null; then
        echo "ERROR: unknown function '$fn'" >&2
        exit 1
    fi
    "$fn" "$@"
fi
