#!/bin/bash
# BUILD VAULT INDEX: Scans vault/ directories and builds vault/INDEX.md
# A searchable index of all vault entries with title, date, status, and area.
#
# Usage: build-index.sh <vault_dir>

set -euo pipefail

VAULT_DIR="${1:?Usage: build-index.sh <vault_dir>}"
INDEX_FILE="${VAULT_DIR}/INDEX.md"

# Directories to index (relative to vault/)
SEARCH_DIRS="gotchas investigations decisions completed workflows patterns architecture changelog planning evals"

# Start building the index
{
    echo "# Vault Index"
    echo ""
    echo "_Auto-generated by \`build-index.sh\` on $(date +%Y-%m-%d)._"
    echo ""

    for dir in $SEARCH_DIRS; do
        search_path="${VAULT_DIR}/${dir}"
        [ -d "$search_path" ] || continue

        # Check if directory has any markdown files
        file_count=$(find "$search_path" -name "*.md" -type f ! -name "_template.md" ! -name "_example.md" ! -name "INDEX.md" 2>/dev/null | wc -l | tr -d ' ')
        [ "$file_count" -eq 0 ] && continue

        echo "## ${dir}"
        echo ""
        echo "| Title | Date | Status | Area |"
        echo "|-------|------|--------|------|"

        find "$search_path" -name "*.md" -type f ! -name "_template.md" ! -name "_example.md" ! -name "INDEX.md" 2>/dev/null | sort | while read -r filepath; do
            rel_path="${filepath#${VAULT_DIR}/}"

            # Extract title: first # line after frontmatter
            title=$(awk '
                /^---$/ { fm++; next }
                fm >= 2 && /^#/ { gsub(/^#+ */, ""); print; exit }
                fm < 2 && /^#/ { gsub(/^#+ */, ""); print; exit }
            ' "$filepath" 2>/dev/null || echo "$(basename "$filepath" .md)")

            # Extract date from frontmatter or filename
            date=$(awk '/^---$/{n++; next} n==1 && /^date:/{gsub(/^date: */, ""); print; exit}' "$filepath" 2>/dev/null || echo "")
            if [ -z "$date" ]; then
                # Try to extract date from filename (YYYY-MM-DD pattern)
                date=$(echo "$(basename "$filepath")" | grep -oE '^[0-9]{4}-[0-9]{2}(-[0-9]{2})?' || echo "-")
            fi
            [ -z "$date" ] && date="-"

            # Extract status from frontmatter
            status=$(awk '/^---$/{n++; next} n==1 && /^status:/{gsub(/^status: */, ""); print; exit}' "$filepath" 2>/dev/null || echo "-")
            [ -z "$status" ] && status="-"

            # Extract area from frontmatter
            area=$(awk '/^---$/{n++; next} n==1 && /^area:/{gsub(/^area: */, ""); print; exit}' "$filepath" 2>/dev/null || echo "-")
            [ -z "$area" ] && area="-"

            echo "| [${title}](${rel_path}) | ${date} | ${status} | ${area} |"
        done

        echo ""
    done
} > "$INDEX_FILE"

entry_count=$(grep -c '^\|' "$INDEX_FILE" | head -1 || echo "0")
# Subtract header rows (2 per table: header + separator)
table_count=$(grep -c '^## ' "$INDEX_FILE" || echo "0")
entry_count=$((entry_count - table_count * 2))
[ "$entry_count" -lt 0 ] && entry_count=0

echo "Vault index built: ${INDEX_FILE} (${entry_count} entries)"
