#!/bin/bash
# PRE-COMPACT HOOK: Save working context before compaction destroys it
#
# Context compaction wipes mid-task state. This hook extracts key information
# from the conversation transcript and saves it to a recovery file that the
# session-start-loader will pick up if the session continues.
#
# Saved information:
# - Task description (from first substantial user prompt)
# - Files modified this session (from .sentinel/modified-files.txt)
# - Todo list state (if TodoWrite was used)
# - Tool usage summary

set -euo pipefail

INPUT=$(cat)
TRANSCRIPT_PATH=$(echo "$INPUT" | jq -r '.transcript_path // empty')
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"')
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')

VAULT_DIR="${CWD}/vault"

# Graceful exit if vault doesn't exist
if [ ! -d "$VAULT_DIR" ]; then
    exit 0
fi

RECOVERY_DIR="${VAULT_DIR}/session-recovery"
TIMESTAMP=$(date +%Y-%m-%dT%H-%M-%S)
RECOVERY_FILE="${RECOVERY_DIR}/${TIMESTAMP}-${SESSION_ID:0:8}.md"

mkdir -p "$RECOVERY_DIR"

# Extract context from transcript (last 200 lines for manageability)
FILES_MODIFIED=""
TOOL_CALLS=""
TASK_DESCRIPTION=""
TODO_STATE=""

if [ -n "$TRANSCRIPT_PATH" ] && [ -f "$TRANSCRIPT_PATH" ]; then
    RECENT_CONTEXT=$(tail -200 "$TRANSCRIPT_PATH" 2>/dev/null || echo "")

    if [ -n "$RECENT_CONTEXT" ]; then
        # Extract file paths that were edited
        FILES_MODIFIED=$(echo "$RECENT_CONTEXT" | grep -oE '"file_path"\s*:\s*"[^"]*"' | sed 's/"file_path"\s*:\s*"//;s/"$//' | sort -u | head -20 || echo "")

        # Extract tool usage counts
        TOOL_CALLS=$(echo "$RECENT_CONTEXT" | grep -oE '"tool_name"\s*:\s*"[^"]*"' | sed 's/"tool_name"\s*:\s*"//;s/"$//' | sort | uniq -c | sort -rn | head -10 || echo "")

        # Extract task description (first substantial user prompt)
        TASK_DESCRIPTION=$(echo "$RECENT_CONTEXT" | grep -oE '"content"\s*:\s*"[^"]{20,200}"' | head -1 | sed 's/"content"\s*:\s*"//;s/"$//' || echo "")

        # Extract most recent TodoWrite state
        TODO_STATE=$(echo "$RECENT_CONTEXT" | grep -oE '"todos"\s*:\s*\[[^]]*\]' | tail -1 | head -c 500 || echo "")
    fi
fi

# Also pull files from the sentinel tracker (more reliable than transcript parsing)
SENTINEL_FILES="${CWD}/.sentinel/modified-files.txt"
if [ -f "$SENTINEL_FILES" ]; then
    SENTINEL_LIST=$(cat "$SENTINEL_FILES" | head -30)
    if [ -n "$SENTINEL_LIST" ]; then
        FILES_MODIFIED="${SENTINEL_LIST}"
    fi
fi

# Write the recovery file
cat > "$RECOVERY_FILE" << RECOVERY_EOF
---
type: session-recovery
session_id: ${SESSION_ID}
timestamp: ${TIMESTAMP}
trigger: pre-compaction
status: active
---

# Session Recovery -- ${TIMESTAMP}

## Context Saved Before Compaction

This file was auto-generated by the pre-compact hook to preserve context
that would otherwise be lost during compaction.

## Task Description

${TASK_DESCRIPTION:-"(not detected -- check conversation)"}

## Progress (TodoWrite State)

${TODO_STATE:-"(no todo list detected)"}

## Files Being Worked On

${FILES_MODIFIED:-"(none detected)"}

## Tool Usage Summary

${TOOL_CALLS:-"(none detected)"}

## IMPORTANT FOR NEXT CONTEXT WINDOW

After compaction, the agent should:
1. Read this file to recover context about what was being worked on
2. Check vault/investigations/ for any open investigations related to current work
3. Check vault/gotchas/ for known pitfalls in the areas being modified
4. Continue from where the session left off

RECOVERY_EOF

# Output message for post-compaction context injection
echo "PRE-COMPACT: Session context saved to ${RECOVERY_FILE}. After compaction, read this file to recover working state."

exit 0
